// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for CheckerPlayFrom.
const (
	CheckerPlayFromBar CheckerPlayFrom = "bar"
	CheckerPlayFromN1  CheckerPlayFrom = "1"
	CheckerPlayFromN10 CheckerPlayFrom = "10"
	CheckerPlayFromN11 CheckerPlayFrom = "11"
	CheckerPlayFromN12 CheckerPlayFrom = "12"
	CheckerPlayFromN13 CheckerPlayFrom = "13"
	CheckerPlayFromN14 CheckerPlayFrom = "14"
	CheckerPlayFromN15 CheckerPlayFrom = "15"
	CheckerPlayFromN16 CheckerPlayFrom = "16"
	CheckerPlayFromN17 CheckerPlayFrom = "17"
	CheckerPlayFromN18 CheckerPlayFrom = "18"
	CheckerPlayFromN19 CheckerPlayFrom = "19"
	CheckerPlayFromN2  CheckerPlayFrom = "2"
	CheckerPlayFromN20 CheckerPlayFrom = "20"
	CheckerPlayFromN21 CheckerPlayFrom = "21"
	CheckerPlayFromN22 CheckerPlayFrom = "22"
	CheckerPlayFromN23 CheckerPlayFrom = "23"
	CheckerPlayFromN24 CheckerPlayFrom = "24"
	CheckerPlayFromN3  CheckerPlayFrom = "3"
	CheckerPlayFromN4  CheckerPlayFrom = "4"
	CheckerPlayFromN5  CheckerPlayFrom = "5"
	CheckerPlayFromN6  CheckerPlayFrom = "6"
	CheckerPlayFromN7  CheckerPlayFrom = "7"
	CheckerPlayFromN8  CheckerPlayFrom = "8"
	CheckerPlayFromN9  CheckerPlayFrom = "9"
)

// Valid indicates whether the value is a known member of the CheckerPlayFrom enum.
func (e CheckerPlayFrom) Valid() bool {
	switch e {
	case CheckerPlayFromBar:
		return true
	case CheckerPlayFromN1:
		return true
	case CheckerPlayFromN10:
		return true
	case CheckerPlayFromN11:
		return true
	case CheckerPlayFromN12:
		return true
	case CheckerPlayFromN13:
		return true
	case CheckerPlayFromN14:
		return true
	case CheckerPlayFromN15:
		return true
	case CheckerPlayFromN16:
		return true
	case CheckerPlayFromN17:
		return true
	case CheckerPlayFromN18:
		return true
	case CheckerPlayFromN19:
		return true
	case CheckerPlayFromN2:
		return true
	case CheckerPlayFromN20:
		return true
	case CheckerPlayFromN21:
		return true
	case CheckerPlayFromN22:
		return true
	case CheckerPlayFromN23:
		return true
	case CheckerPlayFromN24:
		return true
	case CheckerPlayFromN3:
		return true
	case CheckerPlayFromN4:
		return true
	case CheckerPlayFromN5:
		return true
	case CheckerPlayFromN6:
		return true
	case CheckerPlayFromN7:
		return true
	case CheckerPlayFromN8:
		return true
	case CheckerPlayFromN9:
		return true
	default:
		return false
	}
}

// Defines values for CheckerPlayTo.
const (
	CheckerPlayToN1  CheckerPlayTo = "1"
	CheckerPlayToN10 CheckerPlayTo = "10"
	CheckerPlayToN11 CheckerPlayTo = "11"
	CheckerPlayToN12 CheckerPlayTo = "12"
	CheckerPlayToN13 CheckerPlayTo = "13"
	CheckerPlayToN14 CheckerPlayTo = "14"
	CheckerPlayToN15 CheckerPlayTo = "15"
	CheckerPlayToN16 CheckerPlayTo = "16"
	CheckerPlayToN17 CheckerPlayTo = "17"
	CheckerPlayToN18 CheckerPlayTo = "18"
	CheckerPlayToN19 CheckerPlayTo = "19"
	CheckerPlayToN2  CheckerPlayTo = "2"
	CheckerPlayToN20 CheckerPlayTo = "20"
	CheckerPlayToN21 CheckerPlayTo = "21"
	CheckerPlayToN22 CheckerPlayTo = "22"
	CheckerPlayToN23 CheckerPlayTo = "23"
	CheckerPlayToN24 CheckerPlayTo = "24"
	CheckerPlayToN3  CheckerPlayTo = "3"
	CheckerPlayToN4  CheckerPlayTo = "4"
	CheckerPlayToN5  CheckerPlayTo = "5"
	CheckerPlayToN6  CheckerPlayTo = "6"
	CheckerPlayToN7  CheckerPlayTo = "7"
	CheckerPlayToN8  CheckerPlayTo = "8"
	CheckerPlayToN9  CheckerPlayTo = "9"
	CheckerPlayToOff CheckerPlayTo = "off"
)

// Valid indicates whether the value is a known member of the CheckerPlayTo enum.
func (e CheckerPlayTo) Valid() bool {
	switch e {
	case CheckerPlayToN1:
		return true
	case CheckerPlayToN10:
		return true
	case CheckerPlayToN11:
		return true
	case CheckerPlayToN12:
		return true
	case CheckerPlayToN13:
		return true
	case CheckerPlayToN14:
		return true
	case CheckerPlayToN15:
		return true
	case CheckerPlayToN16:
		return true
	case CheckerPlayToN17:
		return true
	case CheckerPlayToN18:
		return true
	case CheckerPlayToN19:
		return true
	case CheckerPlayToN2:
		return true
	case CheckerPlayToN20:
		return true
	case CheckerPlayToN21:
		return true
	case CheckerPlayToN22:
		return true
	case CheckerPlayToN23:
		return true
	case CheckerPlayToN24:
		return true
	case CheckerPlayToN3:
		return true
	case CheckerPlayToN4:
		return true
	case CheckerPlayToN5:
		return true
	case CheckerPlayToN6:
		return true
	case CheckerPlayToN7:
		return true
	case CheckerPlayToN8:
		return true
	case CheckerPlayToN9:
		return true
	case CheckerPlayToOff:
		return true
	default:
		return false
	}
}

// Defines values for MoveArgsPlayer.
const (
	O MoveArgsPlayer = "o"
	X MoveArgsPlayer = "x"
)

// Valid indicates whether the value is a known member of the MoveArgsPlayer enum.
func (e MoveArgsPlayer) Valid() bool {
	switch e {
	case O:
		return true
	case X:
		return true
	default:
		return false
	}
}

// Board defines model for Board.
type Board struct {
	// O Number of checkers in each point on the board.
	O CheckerLayout `json:"o"`

	// X Number of checkers in each point on the board.
	X CheckerLayout `json:"x"`
}

// CheckerLayout Number of checkers in each point on the board.
type CheckerLayout struct {
	N1  *int `json:"1,omitempty"`
	N10 *int `json:"10,omitempty"`
	N11 *int `json:"11,omitempty"`
	N12 *int `json:"12,omitempty"`
	N13 *int `json:"13,omitempty"`
	N14 *int `json:"14,omitempty"`
	N15 *int `json:"15,omitempty"`
	N16 *int `json:"16,omitempty"`
	N17 *int `json:"17,omitempty"`
	N18 *int `json:"18,omitempty"`
	N19 *int `json:"19,omitempty"`
	N2  *int `json:"2,omitempty"`
	N20 *int `json:"20,omitempty"`
	N21 *int `json:"21,omitempty"`
	N22 *int `json:"22,omitempty"`
	N23 *int `json:"23,omitempty"`
	N24 *int `json:"24,omitempty"`
	N3  *int `json:"3,omitempty"`
	N4  *int `json:"4,omitempty"`
	N5  *int `json:"5,omitempty"`
	N6  *int `json:"6,omitempty"`
	N7  *int `json:"7,omitempty"`
	N8  *int `json:"8,omitempty"`
	N9  *int `json:"9,omitempty"`
	Bar *int `json:"bar,omitempty"`
}

// CheckerPlay Move coordinates
type CheckerPlay struct {
	// From Point where the checker is currently
	From CheckerPlayFrom `json:"from"`

	// To Point where the checker will move
	To CheckerPlayTo `json:"to"`
}

// CheckerPlayFrom Point where the checker is currently
type CheckerPlayFrom string

// CheckerPlayTo Point where the checker will move
type CheckerPlayTo string

// EvalInfo Evaluation details
type EvalInfo struct {
	// Cubeful Was cube decision considered?
	Cubeful bool `json:"cubeful"`

	// Plies How many turns ahead was considered. Typically 3, but may terminate earlier if probabilty already looks certain.
	Plies int `json:"plies"`
}

// Evaluation Score of the move
type Evaluation struct {
	// Diff Equity difference compared to the best move
	Diff float32 `json:"diff"`

	// Eq Equity value of the move relative to zero (neutral)
	Eq float32 `json:"eq"`

	// Info Evaluation details
	Info *EvalInfo `json:"info,omitempty"`

	// Probability Probabilty of win/lose after making this move. Values are percentage proportions of 1, i.e. 1 means 100% certainty, 0.5 means 50% etc.
	Probability *Probability `json:"probability,omitempty"`
}

// Move Backgammon move
type Move struct {
	// Evaluation Score of the move
	Evaluation *Evaluation    `json:"evaluation,omitempty"`
	Play       *[]CheckerPlay `json:"play,omitempty"`
}

// MoveArgs defines model for MoveArgs.
type MoveArgs struct {
	Board Board `json:"board"`

	// Cubeful Is doubling cube in use?
	Cubeful *bool `json:"cubeful,omitempty"`

	// Dice 2-slot array of dice values been thrown
	Dice []int `json:"dice"`

	// MaxMoves Max number of moves to return. if not supplied means return all available moves.
	MaxMoves *int `json:"max-moves,omitempty"`

	// Player Player on roll
	Player MoveArgsPlayer `json:"player"`

	// Plies Search depth in plies (GNU Backgammon). Higher = stronger but slower.
	Plies *int `json:"plies,omitempty"`

	// ScoreMoves Whether or not to calculate equities for each available move. Takes longer.
	ScoreMoves *bool `json:"score-moves,omitempty"`
}

// MoveArgsPlayer Player on roll
type MoveArgsPlayer string

// Probability Probabilty of win/lose after making this move. Values are percentage proportions of 1, i.e. 1 means 100% certainty, 0.5 means 50% etc.
type Probability struct {
	// Lose Probabilty of losing the game. Always `1 - win`
	Lose float32 `json:"lose"`

	// LoseBG Probabilty of losing a backgammon
	LoseBG float32 `json:"loseBG"`

	// LoseG Probabilty of losing a gammon
	LoseG float32 `json:"loseG"`

	// Win Probabilty of winning the game
	Win float32 `json:"win"`

	// WinBG Probability of winning a backgammon
	WinBG float32 `json:"winBG"`

	// WinG Probability of winning a gammon
	WinG float32 `json:"winG"`
}

// PostGetmovesJSONRequestBody defines body for PostGetmoves for application/json ContentType.
type PostGetmovesJSONRequestBody = MoveArgs

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get moves
	// (POST /getmoves)
	PostGetmoves(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostGetmoves converts echo context to params.
func (w *ServerInterfaceWrapper) PostGetmoves(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostGetmoves(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/getmoves", wrapper.PostGetmoves)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RYbW/bNhD+KwduBVpA9WvSFwPDkHRDGmztArRbPwQBepLONhuKVEjKjlb4vw9HybJl",
	"S0n6aV8Cmy/Hu+eee+7i7yIxWW40ae/E7LtwyZIyDB/PDdqUP+TW5GS9pLBs+M/PluZiJn4a7m4P66vD",
	"d0tKbsn+iaUpvNhE4v4Hb2wiYemukJZSMbsWRrCJm0j4MicxEyb+Rkkw3L43+y5ScomVuZdGi5n4WGQx",
	"WTBzSKqDDqQGwmQJuZHag9HglwQxBzoQkaB7zHJFbGk8FbPTSExOxGwSiVfhyxsxm26iAzjG/Kf2TGpP",
	"C7Ls2njUs953ftKzPu1ZP+lZP+1Zf9Wz/rpn/U3P+tvu9R73Jz0wTHpgmPTZ6YFh0gNDz/Ge0z2Y9UDW",
	"g1gPYD14xWi7Njb9LL9SWB5z/INZESTG2FRq9OTEIT/n1mTH164C/9dLshRKoC4QkA6SwlrSXpVcELrI",
	"uATHgjPMsDKGDBijw1Bw3BxkYHygd+ByIG5gaaBk4F8gW2BWoFEgR2BCSHvIcUhoBc6u3p23Ui8YCW+e",
	"HslaKgWZWdH/F4aZzzvCOFA3z/IWktSlcL+vUF3qeUfcvFMgf4GUPEp1nPqkiGleqOO7X5DTHBOklEjH",
	"JhKjnUzJUvrrvg7OUTlq3IqNUYSa/cpV/Ubb8Huzhgx1Cb6w2gEuCVNY82uN/QF8LnOZoFIlTCOICw8Z",
	"luDJZoHBQGiVZCrOIbcmxlgqXwIqS5iWoIy5dZCQ9Sh1S7OnUVc17UO9xWPrfh/gFazH0X1KjCVuJ8yz",
	"mlptxFM5n3ek6q6QvgTeJEs64YLNcrSUgjdVByLnG7JuAxo17unQyNg9uus1z463vANLCr1cEb/yL1kD",
	"zzUV3qJ60XpmMD592/GUrGn3UONu6Fm1xZAs6cvHrl3tHT1MEt2JqMKxKz0sd8cInGNyu8AsM7o7LdRK",
	"6mMB1ScDyyvJlZ4y98QhJsj0TsbRWiy7dZ1jObMLdzxixdvJ66H3qvFsE7XLfI6F8k3htmG6dJCaIlZS",
	"L6rylxoKR1zxxxWeyqQD6clLp4yHEBVzjU9VzHMQE/E8Zc1a7/PrehqNb6Idhhney4z1+FUkMqmrz+Oo",
	"o0dmeH9Z3ZqEo7svbXDDyZec+Q5J+oD3oJtBMBzierDEEjVgldHGgyty1oQUMkLt6l1ApQBXKBXGqqop",
	"dyg5TQSjrgiYQGQ7mlZY5/nTGqX2OtQ9tw1mfvNGWDrqhHv6W2d8fJjtT4Q2WUJKuV9ypsMVeH7x8W/Y",
	"1cuLAbyXiyVZ+AWct0YvyAZNdsqsybainUS73J08FrljrdzPSe2mt8URL78sybMLxoZceAMJqqRQoRuw",
	"uLHjc2Or0b2dkAF8xltyoILrgw4qH+hLVVs1v5sMdWnNVVvQDjK4a01mDmuph8o4Apx7spDhLdeYX0pX",
	"O/lPVSJoCXKyCWmPC+L+lhvLFh1bGUcgBzSAcc3C8Wj0bNvqfBnBaHBa75yOngH5ZHCkdOzEY84q4yrv",
	"CBaY0QDO1BpLB1/H8JIj+druDqejaUd34IfOL574FELcMK5tfDR63WP86ba77I5POsyupX5CIvU+OG2r",
	"J29fd5t9CAnZtvwQFm+6rf+I8U4wpsduH1QFQ1O/tQ2oSoPYZqNJ+XGpbPamhbab75o6biacqpIRFnJF",
	"ek+JIDdOhmuR8NIH6dvb/UIxnF1dikisyLrK+ngwGowYI5OTxlyKmZiGpUjk6JehIIYL8o0K5cZ1/Exw",
	"QV2eBZ0AFX5aANRp1epqueaSC1PCZRr+BXH+YvtMhSs5f27SoBuJ0Z50eBe5ySTh4vCbq6aRqp0/1uyb",
	"WWGzqVLncqNdFdVkNPqhd540zYRB63iM2Rxq919/BC65IsvQlvtoch6Rp5trcYEZnWlUpZNO3AQrjiwn",
	"UsyuD9PxW9UqoDohIlFYJWZiiLkcrsZic7P5LwAA//9LCw0BtBIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
